name: Nix + Wasm example project

on:
  pull_request:
  push:
    branches:
      - main

env:
  REPO: ${{ github.event.repository.name }}

jobs:
  check:
    environment: check
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v1
        with:
          extra-conf: |
            binary-caches = https://cache.nixos.org https://${{ secrets.CACHIX_CACHE }}.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ${{ secrets.CACHIX_TRUSTED_PUBLIC_KEY }}
            trusted-substituters = https://cache.nixos.org https://${{ secrets.CACHIX_CACHE }}.cachix.org
            trusted-users = root runner
      - name: Set up Nix environment
        run: |
          nix develop --command direnv allow
          eval "$(nix develop --command direnv export bash)"
          echo "$PATH" >> $GITHUB_PATH
      - name: Binary cache setup
        run: |
          cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
          cachix use ${{ secrets.CACHIX_CACHE }}
      - name: Build all
        run: nix build -L
      - name: Run fully test suite
        run: run-test-suite
      - name: Cache development environment
        run: |
          nix develop --profile ${{ env.REPO }}
          cachix push ${{ secrets.CACHIX_CACHE }} ${{ env.REPO }}
      - name: Cache build artifacts
        run: |
          nix flake archive --json \
            | jq -r '.path,(.inputs|to_entries[].value.path)' \
            | cachix push "${{ secrets.CACHIX_CACHE }}"
